language: node_js

sudo: false
dist: trusty

node_js:
  - '8'

cache:
  directories:
    - node_modules

branches:
  only:
  - master

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run build
  - npm test
git:
  depth: 1
