export const CommonOptions = {
  classKind: 'kind',
  name: 'name',
  platform: 'platform',
  description: 'description',
  children: 'children',
  value: 'value',
  instance: 'instance',
  kind: 'kind',
  members: 'members',
  methodType: 'returns',
  params: 'params',
  paramType: 'type',
  properties: 'properties',
  examples: 'examples',
  type: 'type',
  tags: 'tags',
  title: 'title',
  static: 'static'
};