export const CO = {
  children: 'children',
  primKind: 'kindString',
  name: 'name',
  decorators: 'decorators',
  declaration: 'declaration',
  comment: 'comment',
  type: 'type',
  elementType: 'elementType',
  flags: 'flags',
  isStatic: 'isStatic',
  signatures: 'signatures',
  indexSignature: 'indexSignature',
  parameters: 'parameters',
  tag: 'tag',
  tags: 'tags',
  text: 'text',
  description: 'description',
  shortDescription: 'shortDescription',
  returns: 'returns',
  setSignature: 'setSignature',
  arguments: 'arguments',
  bindingPropertyName: 'bindingPropertyName',
  typeArguments: 'typeArguments',
  getSignature: 'getSignature',
  inheritedFrom: 'inheritedFrom',
  shortText: 'shortText',
};
